### ISSUE TITLE
Add in quick zoom out

### ISSUE THREAD

**Issue by owopeachy** [Kramar1337/GenshinImpact-AHK-flex#22]
This tool is great, and I am amazed at how good you are at ahk lol, 
So we know the camera is fucking garbage and zooms itself in after using skills constantly, i have this script for zooming out on left mouse click, maybe it fits within the scope of this tool and you can add it in some way?  Thanks!
```#MaxThreadsPerHotkey 2
#SingleInstance Force
DetectHiddenWindows, On
#IfWinActive, ahk_class UnityWndClass
~*RButton::
Toggle = 0
loop 200
{
If Toggle = 1
{
;ToolTip
break
}
SendInput {WheelDown}
}
Sleep 50
return
*~Escape::
Toggle = 1
*~LAlt::
Toggle = 1
*~LControl::
Toggle = 1
*~L::
Toggle = 1
*~LWin::
Toggle = 1

**Comment by Kramar1337** [comment]
where to begin...

The camera zoom in this game is really rubbish. Changing the game settings helps for most characters, but for example Xiao does not work.

For another game (TOF) I already tried to make a script to move the camera away. Nothing good came of it. I wanted to make 1 stream that will move the camera, it's not clear how to filter it so that it does not interfere with the game.
Autohotkey is a single-threaded language and it cannot execute more than 1 thread at the same time, this limitation can be bypassed by multiprocessing, bad solution but it works.

Binding the mouse button "RButton" is also a bad idea. Sometimes it doesn't work consistently. I try not to use mouse buttons.

What to do?

In my script there is a function "F - quick selection of loot" and there is built-in scrolling the mouse wheel down and this can be used to move the camera away.
Or
Run my script and your script.
