### ISSUE TITLE
Update for fishing

### ISSUE THREAD

**Issue by odano27** [Kramar1337/GenshinImpact-AHK-flex#23]
Source: https://www.hoyolab.com/article/828686
Here's a draft fishing guide update I made, you can use this or make a new one.
![genOverlay12](https://user-images.githubusercontent.com/93634782/222692079-f5de5ca5-68bf-43d1-81a8-e8ea9f5b800a.png)

**Comment by Kramar1337** [comment]
Hello.
I don't like your draft.
1. Low resolution image is used, low resolution of the original image by hoyolab. nothing can be done about it
2. outdated manual. no new fish from new region
3. careless gluing, I can fix it but it makes no sense due to the above reasons

denied
as soon as there is an update on hoyolab with new fish let me know.
