### ISSUE TITLE
How does the auto fishing work?

### ISSUE THREAD

**Issue by lmtivy** [Kramar1337/GenshinImpact-AHK-flex#25]

**Comment by Kramar1337** [comment]
https://github.com/Kramar1337/GenshinImpact-AHK-flex/wiki/EN

**Comment by Kramar1337** [comment]
X - Fishing

Double quick press of "X" will start the algorithm for finding pixels on the screen

A single click will stop the algorithm

We cast a fishing rod, catch fish and then the script itself clicks the mouse at the right timing, at sunset-dawn, the colors of fishing and the colors of the environment can merge and the script will start to miss (turn away from sunset?). In "data\genConfig.ini" there is a delay of "OptimizationFis=1" for maximum speed, you can set "0" but it greatly suffocates the percentage(3%) or set "50" but it will work slower.

**Comment by lmtivy** [comment]
https://youtu.be/vTZPr1TE17s
I followed the instructions, but the mouse won't click at all.

**Comment by Kramar1337** [comment]
I have not used fishing for a long time, I thought that something has changed in the game since then. Everything remains as before.
The automatic fishing script works properly for me and my friends. I just went in, teleported to the same place as in the video and everything works.

I don't know why it doesn't work for you, but I can suggest some solutions to the problem.

What to do?
Remove Autohotkey
Install Autohotkey following the instructions. "Custom installation" => "Unicode 64" => All checkboxes => "Install"
Download the script again and run with standard settings.
Graphics settings and screen resolution do not matter, but if you use reshade or other graphic filters
auto fishing will not work.
Try running any macro to make sure the script is working, for example select "Numpad 1 - AutoAttack" and activate "V - Macro Key"

If that didn't help:
You can experiment with the settings of the configuration file "data\genConfig.ini" increase the value of "OttenokFis=5"

If all else fails, then open the script tab "Links" => "Debug information" copy and send to me.

Last measure:
You can take a screenshot of the screen and manually cut out a small strip of the horizontal strip "data\find.png" and the vertical strip "data\find2.png"

**Comment by lmtivy** [comment]
[Debug.txt](https://github.com/Kramar1337/GenshinImpact-AHK-flex/files/11149483/Debug.txt)
Here's my debug file. I tried everything in your guide but got no luck. I've been using another auto-fishing project https://github.com/babalae/genshin-fishing-toy without any problems. (No, I did not run them at the same time.)
I have no problem using other macros/functions in your script.

**Comment by lmtivy** [comment]
It worked! Thank you so much!
