### ISSUE TITLE
Continuing.

### ISSUE THREAD

**Issue by TharakLoar** [Kramar1337/GenshinImpact-AHK-flex#8]
Hey!
Not sure if you saw my comment on the other topic, since it was closed.
But I've sent you some money to that PayPal account, enjoy a nice drink! :)

Also, you don't need to fix it just because I sent money or anything, but if it's something easy to fix...

1. The "F" script dashes by itself while the toggle is on. (to test this, just toggle it on and run around a bit)
2. To the "F" script would it be easy to implement the "hold F" just like on the normal script (and also toggle it off, if on) and only double click turns the toggle on?

Thank you ~~

**Comment by Kramar1337** [comment]
https://pastebin.com/pfHdTjFg
Added \ changed:
Hold the "F" button
Double click turns on spam "F"
Checking the game window

Buttons:
F - Fast loot
End - Exit app
Variables:
34 line "FIXchat: = 1" if the game chat or map is open or there is a dialogue with the NPC, then the script is waiting
"ScRandomT: = 1" inserts random delays

**Comment by TharakLoar** [comment]
Oh, is the FIXchat the reason the character dashes sometimes while the toggle is on?
Haven't tested it with that option off yet.

Works great tho! Thank you~~
Hope the money reached you alright :)

**Comment by Kramar1337** [comment]
The money has arrived, thanks.

"character dashes" if I understand correctly you have disabled user account control (UAC) and because of this SendInput mode accidentally squeezes Shift in a loop.
35 line, variable:
"Global metodVvoda = 1" - SendInput
"Global metodVvoda = 2" - SendPlay (UAC off only) <=

**Comment by TharakLoar** [comment]
Hum... I do not have UAC off, tried mode 2 but it doesnt work (because its not off)

**Comment by Kramar1337** [comment]
At first I didn't understand... Then I understood.
Hidden AutoHotkey Problems
If more than one script is run using the loop, then the "Shift" is accidentally pressed. The solution to this problem is as follows:
Set "Global metodVvoda = 2"
Run the script through "Run with UI Access" (Right click on the script and select the "Run with UI Access" item in the context menu)

**Comment by Kramar1337** [comment]
checked everything works

**Comment by TharakLoar** [comment]
I'm not sure where to find this "run with UI access"
Do you mean "run as administrator"? The scripts were always running as adminstrator :( so nothing changed

**Comment by Kramar1337** [comment]
https://prnt.sc/1szopss
https://prnt.sc/1szosfy

**Comment by TharakLoar** [comment]
Fixed!!!
You are the best! :)
Thank you very much~~ Everything is 1000% perfect now.

**Comment by Kramar1337** [comment]
It turned out not very convenient. But this is the easiest way.
So I didn't want to add this to the main script.
